<?php

namespace Vegfund\Jotta\Tests;

use PHPUnit\Framework\TestCase;
use Vegfund\Jotta\Jotta;
use Vegfund\Jotta\Tests\Support\AssertExceptions;
use Vegfund\Jotta\Tests\Support\JottaTestTrait;

/**
 * Class JottaTestCase.
 */
class JottaTestCase extends TestCase
{
    use AssertExceptions;
    use JottaTestTrait;

    public function tearDown(): void
    {
        $jsonList = json_decode(file_get_contents(__DIR__.DIRECTORY_SEPARATOR.'temp.json'), true);
        $client = $this->jotta();

        foreach($jsonList as $item) {

        }

        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $filename
     *
     * @return string
     */
    protected function tempPath($filename = '')
    {
        return __DIR__.DIRECTORY_SEPARATOR.'temp'.DIRECTORY_SEPARATOR.$filename;
    }

    /**
     * @param $path
     * @param $mountPoint
     */
    protected function addToTempList($path, $mountPoint = Jotta::MOUNT_POINT_ARCHIVE)
    {
        $jsonList = json_decode(file_get_contents(__DIR__.DIRECTORY_SEPARATOR.'temp.json'), true);
        $jsonList[] = [
            'path' => $path,
            'mount_point' => $mountPoint
        ];

        $f = fopen(__DIR__.DIRECTORY_SEPARATOR.'temp.json', 'w');
        fwrite($f, json_encode($jsonList, JSON_PRETTY_PRINT));
        fclose($f);
    }
}
