<?php

namespace Vegfund\Jotta\Tests\Support;

use Vegfund\Jotta\Client\Scopes\DirectoryScope;
use Vegfund\Jotta\Jotta;
use Vegfund\Jotta\JottaClient;
use Vegfund\Jotta\Tests\Mock\JottaApiV1Mock;

class DirectoryScopeExtended extends DirectoryScope
{
    public function __construct(JottaClient $client = null, $mountPoint = Jotta::MOUNT_POINT_ARCHIVE, $basePath = '', $device = Jotta::DEVICE_JOTTA)
    {
        parent::__construct(new JottaClient(getenv('JOTTA_USERNAME'), getenv('JOTTA_PASSWORD'), (new JottaApiV1Mock())->getMock()), $mountPoint, $basePath, $device);
    }

    public function getDirContents($localPath, &$results = [])
    {
        parent::getDirContents($localPath, $results); // TODO: Change the autogenerated stub
    }
}